---

- name: check if nexus is configured with repo {{ proxy_repo.name }}
  uri:
    url: http://{{ app_name }}-{{ ocp_project }}.{{ ocp_domain }}/content/repositories/{{ proxy_repo.name }}/
    status_code: 200,404
  register: result
  ignore_errors: true
  changed_when: false

- name: proxy repo template
  template:
    src: "{{ nexus_proxy_repo_template }}"
    dest: "{{ work_dir }}/nexus-proxy-repo.json"
  changed_when: false

- name: configure proxy repo {{ proxy_repo.name }}
  block:
  - name: configure proxy repo
    uri:
      url: http://{{ app_name }}-{{ ocp_project }}.{{ ocp_domain }}/service/local/repositories
      method: POST
      status_code: 201
      body_format: json
      body: "{{ lookup('file', repo_template) }}"
      force_basic_auth: yes
      user: "{{ nexus_admin_user }}"
      password: "{{ nexus_admin_password }}"
    vars:
      repo_template: "{{ work_dir }}/nexus-proxy-repo.json"
  - name: get public group
    uri:
      url: http://{{ app_name }}-{{ ocp_project }}.{{ ocp_domain }}/service/local/repo_groups/public
      method: GET
      status_code: 200
      headers:
        Accept: application/json
      return_content: true
      force_basic_auth: yes
      user: "{{ nexus_admin_user }}"
      password: "{{ nexus_admin_password }}"
    register: public_group_response
  
  - name: add repo to public group
    shell: |
      echo {{ public_group_response.content|to_json }} > {{ work_dir }}/group-{{ proxy_repo.name }}.json
      sed -i 's/\"repositories\":\[/\"repositories\":[{\"id\": \"{{ proxy_repo.name }}\"},/g' {{ work_dir }}/group-{{ proxy_repo.name }}.json
  - name: put public group
    uri:
      url: http://{{ app_name }}-{{ ocp_project }}.{{ ocp_domain }}/service/local/repo_groups/public
      method: PUT
      status_code: 200
      body_format: json
      body: "{{ lookup('file', group_template) }}"
      force_basic_auth: yes
      user: "{{ nexus_admin_user }}"
      password: "{{ nexus_admin_password }}"
    vars:
      group_template: "{{ work_dir }}/group-{{ proxy_repo.name }}.json"
  when: result.status == 404
