---

- name: delete nexus deployment
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ gapp_name }}"
    namespace: "{{ ocp_project }}"
    kind: deployment

- name: delete nexus route
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ gapp_name }}"
    namespace: "{{ ocp_project }}"
    kind: route

- name: delete nexus service
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ gapp_name }}"
    namespace: "{{ ocp_project }}"
    kind: service

- name: delete nexus pvc
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ nexus_pvc_name }}"
    namespace: "{{ ocp_project }}"
    kind: pvc

- name: delete project
  oc_project:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ ocp_project }}"
  when: >
    uninstall_delete_project is defined and
    uninstall_delete_project == True
